### ISSUE TITLE
data issues

### ISSUE THREAD

**Issue by Darrell0214** [munsif200/Transformer-Network-for-Short-term-Photovoltaic-Power-Generation-Forecasting#2]
I downloaded the data you mentioned. 
First of all, please help me check if it is this one. 

<img width="678" alt="2" src="https://github.com/munsif200/Transformer-Network-for-Short-term-Photovoltaic-Power-Generation-Forecasting/assets/133560941/ea35da36-1582-4306-aeb2-2890a0f8f199">

<img width="230" alt="image" src="https://github.com/munsif200/Transformer-Network-for-Short-term-Photovoltaic-Power-Generation-Forecasting/assets/133560941/75fb711f-e96c-4b00-870a-241c578399ff">

Secondly, there is no data preprocessing file you mentioned here.

<img width="417" alt="1" src="https://github.com/munsif200/Transformer-Network-for-Short-term-Photovoltaic-Power-Generation-Forecasting/assets/133560941/45663c68-7a8d-4ff5-873d-1450291f9155">

**Comment by munsif200** [comment]
1. We have used The 78-Site_2-eco-Kinetics data
2.  The pre-processing is integrated into training and testing files we don't have a separate file for it.
