### ISSUE TITLE
I can't find the data preprocessing.

### ISSUE THREAD

**Issue by lalalalus** [munsif200/Transformer-Network-for-Short-term-Photovoltaic-Power-Generation-Forecasting#3]
when i run the train .py It appear ValueError: array split does not result in an equal division

**Comment by munsif200** [comment]
Thank you for reaching out and showing interest in our project. Regarding your concern, I'd like to clarify that the pre-processing steps are integrated directly into both the training and testing files. As such, there isn't a separate file dedicated solely to pre-processing.
In addressing the error you've encountered, it's advisable to choose batch sizes in even numbers. Additionally, this error may stem from uneven input features or values, as outlined in the original code and dataset.
Please let us know if you require further assistance or clarification. We're here to help!

**Comment by lalalalus** [comment]
> Thank you for your interest in our work. The pre-processing is integrated into training and testing files we don't have a separate file for it.

Thanks for  your reply very much!
